# Generated by Django 3.1.2 on 2021-04-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(help_text='Website entity name', max_length=100)),
                ('address', models.CharField(help_text='Web address', max_length=100)),
            ],
        ),
    ]
