# Generated by Django 3.1.2 on 2021-04-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnavigate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='id',
        ),
        migrations.AlterField(
            model_name='website',
            name='address',
            field=models.URLField(help_text='Web address', max_length=100),
        ),
        migrations.AlterField(
            model_name='website',
            name='entity',
            field=models.CharField(help_text='Website entity name', max_length=100, primary_key=True, serialize=False),
        ),
    ]
